In [5]:
n = 10

x = [i for i in range(n + 1)]
sum = 0
for i in x:
    #print(i)
    sum += i**2
    #print(sum)

print(sum)

385


In [12]:
import numpy as np

a = np.arange(n+1)
#print(a)

np.sum(a **2)



385

In [14]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
np.random.random((2,5))

array([[0.52760611, 0.80387168, 0.78751804, 0.62375931, 0.30059171],
       [0.99518626, 0.59740001, 0.26387797, 0.03260281, 0.92047466]])

In [17]:
np.random.rand(2,5)

array([[0.78984207, 0.09418995, 0.76408888, 0.81960088, 0.80954743],
       [0.45145674, 0.88080358, 0.15607291, 0.74140629, 0.41624372]])

In [21]:
np.random.seed(1)
np.random.rand(2,3,4)

array([[[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
        [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
        [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01]],

       [[2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01],
        [4.17304802e-01, 5.58689828e-01, 1.40386939e-01, 1.98101489e-01],
        [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01]]])

In [23]:
np.random.normal(5,1000,10)

array([-117.89022552, -930.76943426, -262.88807963,  535.35546674,
       -686.66075173, -391.75352686, -682.17270012, -840.2056415 ,
       -666.24613084,   -7.66459892])

In [28]:
a = np.random.uniform(5,1000,size = (2,5))
print(a)

[[430.95073392 965.01584691 665.12429033 623.58724161 119.17224309]
 [949.74181241 452.66257281 580.49766632 411.09611875 240.84184534]]


In [31]:
a[:1,:3]



array([[430.95073392, 965.01584691, 665.12429033]])

In [32]:
x = np.arange(12).reshape(3,4)
y = np.arange(4).reshape(1,4)

np.concatenate((x,y))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [33]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])